# theme: jekyll-theme-hacker
remote_theme: luxedo/jekyll-theme-potato-hacker
title: Avoid Calamity Game
description: Una caccia al tesoro diversa
lang: it-IT
show_downloads: false
github:
  is_project_page: false
